/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Kayttoliittyma;

import Sovelluslogiikka.Kayttaja;
import Sovelluslogiikka.Kellaritoiminnot;
import javax.swing.JOptionPane;

/**
 * luokka on käyttöliittymän elementti, jossa käyttäjä voi luoda uuden
 * käyttäjätunnuksen
 *
 * @author mikko
 */
public class UusiKayttaja extends javax.swing.JDialog {

    private boolean kayttajaLuotu;
    private Kayttaja kayttaja;
    private Kellaritoiminnot toiminnot;

    /**
     * luo uuden elementin
     *
     * @param parent
     * @param modal
     * @param kt parent-elementin tuntema Kellaritoiminnot-olio
     */
    public UusiKayttaja(java.awt.Frame parent, boolean modal, Kellaritoiminnot kt) {
        super(parent, modal);
        initComponents();
        this.kayttajaLuotu = false;
        this.toiminnot = kt;

    }

    /**
     * lukee käyttäjän antaman syötteen ja luo uuden Kayttajan
     */
    public void luoKayttaja() {
        String nimi = jTextField1.getText();
        String tunnus = jTextField2.getText();
        if (!tarkistaTunnus(tunnus)) {
            return;
        }
        String salasana = new String(jPasswordField1.getPassword());
        if (!tarkistaSalasana(salasana)) {
            return;
        }
        String kopio = new String(jPasswordField2.getPassword());
        if (!tarkistaKopio(kopio, salasana)) {
            return;
        }
        Kayttaja uusi = new Kayttaja(nimi, tunnus, salasana);
        this.kayttaja = uusi;
        this.kayttajaLuotu=true;

    }

    public boolean getKayttajaluotu() {
        return kayttajaLuotu;
    }

    public Kayttaja getKayttaja() {
        return kayttaja;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPasswordField1.setText("jPasswordField1");

        jPasswordField2.setText("jPasswordField2");

        jLabel1.setText("Nimi");

        jLabel2.setText("Käyttäjätunnus (5-20 merkkiä):");

        jLabel3.setText("Salasana(5-20 merkkiä):");

        jLabel4.setText("Vahvista Salasana:");

        jButton1.setText("Lisää käyttäjä");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Palaa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(240, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(56, 56, 56)
                        .addComponent(jButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        luoKayttaja();
        if (kayttajaLuotu) {
            setVisible(false);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        kayttajaLuotu = true;
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

    /**
     * tarkistaa salasanan pituuden
     *
     * @param salasana käyttäjän syöttämä salasana
     */
    private boolean tarkistaSalasana(String salasana) {
        if (salasana.length() < 5 || salasana.length() > 20) {
            virheilmoitus("Salasanassa tulee olla 5-20 merkkiä.");
            return false;
        }
        return true;
    }

    /**
     * tarkistaa tunnuksen pituuden ja onko se varattu
     *
     * @param tunnus käyttäjän syöttämä käyttäjätunnus
     */
    private boolean tarkistaTunnus(String tunnus) {
        if (tunnus.length() > 20 || tunnus.length() < 5) {
            virheilmoitus("Tunnuksessa tulee olla 5-20 merkkiä.");
            return false;
        }
        if (!toiminnot.kayttajatunnusVapaa(tunnus)) {
            virheilmoitus("Käyttäjätunnus on varattu.");
            return false;
        }
        return true;
    }

    /**
     * tarkistaa että salasanan varmennus on sama kuin salasana
     *
     * @param kopio käyttäjän syöttämä varmennus
     * @param salasana käyttäjän syöttämä salasana
     */
    private boolean tarkistaKopio(String kopio, String salasana) {
        if (!kopio.equals(salasana)) {
            virheilmoitus("Salasanan vahvistus ei täsmää.");
            return false;
        }
        return true;
    }

    /**
     * näyttää käyttäjälle virheilmoituksen
     *
     * @param ilmoitus virheilmoituksen teksti
     */
    private void virheilmoitus(String ilmoitus) {
        JOptionPane.showMessageDialog(this, ilmoitus);
    }
}
